name: Primeiro workflow

# Eventos para ativar o workflow
on:
  # quais eventos? Push, Pull Request, merge, rebase, ...
  push:
    branches:
      - main
      - developer
  pull_request:
    branches: [ main, developer ]

# quais s√£o os trabalhos a serem executados pelo workflow ?
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Passo 1"

      - name: Passo 2
        run: echo "Passo 2"

      - run: echo "Passo 3"

  job2:
    name: Job 2
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Passo 1"

      - name: Passo 2
        run: echo "Passo 2"

      - run: echo "Passo 3"
  
